# Utiliser une image officielle de Miniconda comme base
FROM continuumio/miniconda3

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier le fichier environment.yml dans le conteneur
COPY environment.yml .

# Créer l'environnement Conda à partir du fichier environment.yml
RUN conda env create -f environment.yml

# Activer l'environnement Conda et définir ce qu'il se passe au lancement
SHELL ["conda", "run", "-n", "myenv", "/bin/bash", "-c"]

# Copier tout le code de l'application dans le conteneur
COPY . .

# Exposer le port sur lequel l'application va tourner
EXPOSE 5000

# Activer l'environnement Conda et lancer l'application
CMD ["conda", "run", "--no-capture-output", "-n", "myenv", "python", "app.py"]
